initial efforts to convert lnbitsbot-js to lnbitsbot-py
lightningames/lnbitsbot-py pull request #1
Opened 2023-05-20 23:30 UTC by eriknewland

I believe the core functionality is working, but still need to incorporate the buttons from telethon library. Also have a few methods left to solve involving the paylinks. 

bot.py:
api_id and api_hash are from the developer section on telegram. bot_token is from botfather. 

config.yml:
lnbits url, admin_key and in_key are from your lnbits wallet.

Notes:

Had a lot of difficulty with the decode_invoice function, believe the problem was a json parsing issue. Needed to make a slight change to pylnbits/utils.py (which im not sure is advised)

![Screen Shot 2023-05-20 at 3 45 15 PM](https://github.com/lightningames/lnbitsbot-py/assets/114263701/04471cde-08d8-4f25-b456-e6915311880f)
![Screen Shot 2023-05-20 at 3 45 37 PM](https://github.com/lightningames/lnbitsbot-py/assets/114263701/9b8064a5-5322-448f-8bee-8a21de0b6907)

2023-05-22 03:24 UTC, eriknewland commented
I think there was another bug in user_wallet.py with check_invoice

![Screen Shot 2023-05-21 at 5 53 06 PM](https://github.com/lightningames/lnbitsbot-py/assets/114263701/3122389c-1bff-4371-8642-932a4abc7ad5)
![Screen Shot 2023-05-21 at 8 19 38 PM](https://github.com/lightningames/lnbitsbot-py/assets/114263701/83e673a9-1c2a-4fab-bff7-3fd9ad650e67)


Added a "main" /lightning route that displays buttons with the sub-routes/event handlers. You can still access these routes individually with their respective commands (i.e. clicking "create invoice" will trigger the same function as typing "/create_invoice"

Refactored general flow to be a question and answer sequence with bot rather than typing "/create_invoice <amount> <memo>"

Still have a couple methods to handle.

Need to handle exiting an event early (i.e. "quit/back/home" command that overrides current event)

Not sure about the presentation of some of the data that is being retrieving as I am still learning about lightning/lnbits API. 

Added BTC logo to QR code

2023-05-22 22:30 UTC, bitkarrot requested changes

2023-05-22 22:30 UTC, bitkarrot commented on bot.py
> +            "max": max_amount,
max amt depends on server side limitations

2023-05-22 22:30 UTC, bitkarrot commented on bot.py
> +        [Button.inline("🔗 Create PayLink", b"create_paylink")],
suggest renaming PayLink to LNURLp.

2023-05-22 22:31 UTC, bitkarrot commented
@eriknewland someone submitted a PR in the last day or two, this may help resolve the decode issue, https://github.com/lightningames/pylnbits/pull/17/files

2023-05-31 17:01 UTC, eriknewland commented on bot.py
> +            "max": max_amount,
Noted but still a little unclear

2023-05-31 19:54 UTC, eriknewland commented
Deployment to fly.io should work, though functionality is dubious. Couple of main issues.

1. Seems like there may be some kind of session issue with the pylnbits library I need to diagnose. Currently I get a run time error when attempting to create multiple invoices (or access multiple commands) back-to-back.

![Screen Shot 2023-05-31 at 12 48 23 PM](https://github.com/lightningames/lnbitsbot-py/assets/114263701/386712a4-6fe0-46b2-8ca3-07d89420f60e)

2. In that same vein, noticed this issue when attempting to explore multiple commands

![Screen Shot 2023-05-31 at 12 48 11 PM](https://github.com/lightningames/lnbitsbot-py/assets/114263701/ed2818b8-61b1-4849-b04c-02aa1923682f)

What's strange is local deployment and the docker image seem to work fine without these issues. which makes me think that perhaps there's some issue with the fly.toml configuration. Will continue to investigate

2023-05-31 20:55 UTC, eriknewland commented
needed to use `self.session` instead of `async with self.session`. weird this wasnt an issue locally.

2023-06-16 02:12 UTC, merged